#!/bin/sh
. "$(dirname "$0")/_/husky.sh"
. "$(dirname "$0")/helpers/prevent_pushing_to_main.sh"
. "$(dirname "$0")/helpers/prevent_conflict_markers.sh"

prevent_pushing_to_main
prevent_conflict_markers
